// Unlit instanced tile shader for the Pixel Flow board, the destroy-animation cube and the tanks.
// One pass without a LightMode tag (SRPDefaultUnlit) so it renders under both the URP 2D Renderer and Forward.
// Per-instance colour comes from _BaseColor in a MaterialPropertyBlock (linear colour space).
//
// _TileTex is a small data texture (generated by the scene builder) that gives every cube face the glossy
// rounded-tile look: R = shade multiplier for the colour, G = 1 - white highlight amount, A = tile mask (the rounded
// corners are clipped). It is sampled with the object-space x/y of the unit cube (not the mesh UVs), so the front
// face always shows the tile upright regardless of the cube's per-face UV layout. Without a texture (white) the
// shader draws the plain colour.
Shader "PixelFlow/InstancedColor"
{
    Properties
    {
        _BaseColor ("Base Color", Color) = (1, 1, 1, 1)
        _TileTex ("Tile (R shade, G 1-highlight, A mask)", 2D) = "white" {}
    }

    SubShader
    {
        Tags { "RenderPipeline" = "UniversalPipeline" "RenderType" = "TransparentCutout" "Queue" = "AlphaTest" }

        Pass
        {
            Name "InstancedColor"
            ZWrite On
            ZTest LEqual
            Cull Back

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma multi_compile_instancing

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"

            TEXTURE2D(_TileTex);
            SAMPLER(sampler_TileTex);

            UNITY_INSTANCING_BUFFER_START(Props)
                UNITY_DEFINE_INSTANCED_PROP(float4, _BaseColor)
            UNITY_INSTANCING_BUFFER_END(Props)

            struct Attributes
            {
                float4 positionOS : POSITION;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float2 uv         : TEXCOORD0;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            Varyings vert(Attributes input)
            {
                Varyings output;
                UNITY_SETUP_INSTANCE_ID(input);
                UNITY_TRANSFER_INSTANCE_ID(input, output);
                output.positionCS = TransformObjectToHClip(input.positionOS.xyz);
                output.uv = input.positionOS.xy + 0.5;
                return output;
            }

            half4 frag(Varyings input) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(input);
                float4 color = UNITY_ACCESS_INSTANCED_PROP(Props, _BaseColor);
                half4 tile = SAMPLE_TEXTURE2D(_TileTex, sampler_TileTex, input.uv);
                clip(tile.a - 0.5);
                half3 rgb = lerp(half3(1, 1, 1), color.rgb * tile.r, tile.g);
                return half4(rgb, color.a);
            }
            ENDHLSL
        }
    }
}
